# Generated by Django 3.2.3 on 2021-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multipost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('image_to_upload', models.ImageField(upload_to='')),
                ('face', models.BooleanField()),
                ('insta', models.BooleanField()),
            ],
        ),
    ]
