# Generated by Django 3.2.3 on 2021-07-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_lift', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multipost',
        ),
    ]
