# Generated by Django 3.2.3 on 2021-07-12 05:21

from django.db import migrations, models
import social_lift.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_lift', '0002_delete_multipost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('price', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=social_lift.models.filepath)),
            ],
        ),
    ]
