# Generated by Django 3.2.3 on 2021-07-12 05:38

from django.db import migrations, models
import social_lift.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_lift', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=191)),
                ('password', models.TextField(max_length=50)),
                ('caption', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=social_lift.models.filepath)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
