# Generated by Django 3.2.3 on 2021-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_lift', '0004_auto_20210712_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
