# Generated by Django 3.2.3 on 2021-07-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_lift', '0005_alter_post_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, max_length=191, null=True)),
                ('password', models.TextField(blank=True, max_length=50, null=True)),
                ('remail', models.TextField(max_length=191)),
                ('message', models.TextField(max_length=500)),
                ('number', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='post_data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
